// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHtkQEWY5esT86YEAZi2mcKV-C1MvEFr8',
    appId: '1:40431539801:web:f7c4ceb69816857af48348',
    messagingSenderId: '40431539801',
    projectId: 'lanuza-63387',
    authDomain: 'lanuza-63387.firebaseapp.com',
    storageBucket: 'lanuza-63387.appspot.com',
    measurementId: 'G-R9TPSLQLFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5w3S4MC7tMM449c1zIldyzqKv7MCkjFQ',
    appId: '1:40431539801:android:647dcbbbed82307ef48348',
    messagingSenderId: '40431539801',
    projectId: 'lanuza-63387',
    storageBucket: 'lanuza-63387.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdUlsf_qcLJtfH5_qqEdsyskrL6Fi9Vq4',
    appId: '1:40431539801:ios:935934b989e6acd2f48348',
    messagingSenderId: '40431539801',
    projectId: 'lanuza-63387',
    storageBucket: 'lanuza-63387.appspot.com',
    iosClientId:
        '40431539801-0mcvk07loq79ita2khphas5vuunerrqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.lanuzaResident',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdUlsf_qcLJtfH5_qqEdsyskrL6Fi9Vq4',
    appId: '1:40431539801:ios:935934b989e6acd2f48348',
    messagingSenderId: '40431539801',
    projectId: 'lanuza-63387',
    storageBucket: 'lanuza-63387.appspot.com',
    iosClientId:
        '40431539801-0mcvk07loq79ita2khphas5vuunerrqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.lanuzaResident',
  );
}
